name: Unit test

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          
      # ~~~~~~~~~~~~~ Start minio ~~~~~~~~~~~~~
      - name: Launch MinIO
        run: |
          docker run -d --name minio \
            -p 9000:9000 \
            -e MINIO_ROOT_USER=minio_access_key \
            -e MINIO_ROOT_PASSWORD=minio_secret_key \
            -e "MINIO_BROWSER=off" \
            minio/minio:RELEASE.2017-05-05T01-14-51Z server /data
          
          # simple health wait (replace with curl if you prefer)
          for i in {1..30}; do
            if curl -fsS http://localhost:9000/minio/health/live > /dev/null; then
              echo "MinIO is up"; break
            fi
            sleep 1
          done

      # ~~~~~~~~~~~~~ Java setup ~~~~~~~~~~~~~
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'
      - name: Display Java version
        run: java --version
        
      # ~~~~~~~~~~~~~ Test ~~~~~~~~~~~~~
      - name: Run gradle tests
        run: ./gradlew test
