name: Unit test

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          
      # ~~~~~~~~~~~~~ Start minio ~~~~~~~~~~~~~
      - name: Launch MinIO
        run: |
          docker run -d -p 9000:9000 --rm \
            -e "MINIO_ACCESS_KEY=minio_access_key" \
            -e "MINIO_SECRET_KEY=minio_secret_key" \
            -e "MINIO_BROWSER=off" \
            minio/minio:RELEASE.2017-05-05T01-14-51Z server /data
          
          # Wait for HTTP to respond (old builds have no /minio/health/*)
          for i in {1..60}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:9000/ || true)
            if [ "$code" = "200" ] || [ "$code" = "403" ] || [ "$code" = "405" ]; then
              echo "MinIO is up with HTTP $code"
              break
            fi
            sleep 1
          done

      # ~~~~~~~~~~~~~ Java setup ~~~~~~~~~~~~~
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'gradle'
      - name: Display Java version
        run: java --version
        
      # ~~~~~~~~~~~~~ Test ~~~~~~~~~~~~~
      - name: Run gradle tests
        run: ./gradlew test
